server:
  port: 7800

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://dev-app.ebiz4u.co.kr:1433;databasename=ebiz4u
    username: ebiz4u
    password: ghkfWkr

  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      use-new-id-generator-mappings: false